### ISSUE TITLE
Reuse

### ISSUE THREAD

**Issue by ansarimofid** [saurabhjn76/Hackerrank-Solution#1]
What if someone uses your code to submit to hackerrank.

**Comment by saurabhjn76** [comment]
I agree that although these codes are available for help, one can use this for copying, but copy pasting code only spoils the point of the challenge since one don't get to learn anything. It's more rewarding when one find his own way through a challenge.
Also there are numerous solution available online so if one intends to copy anyhow he /she would succeed.Only solution is one need to realize what benefits he/she will be getting.
